unbind C-b
set -g prefix `
bind ` send-prefix

unbind l

bind L last-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind M-h resize-pane -L
bind M-j resize-pane -D
bind M-k resize-pane -U
bind M-l resize-pane -R
bind C-h resize-pane -L 5
bind C-j resize-pane -D 5
bind C-k resize-pane -U 5
bind C-l resize-pane -R 5

bind Space copy-mode

set -g default-terminal "xterm-256color"
set -s escape-time 0
setw -g mode-keys vi
set-option -g history-limit 10000

# Fix the problem where tmux prints "1;2c"
set -sg escape-time 1

set-option -g default-command "reattach-to-user-namespace -l $SHELL"
